### ISSUE TITLE
Feature Request: Support for linux runners

### ISSUE THREAD

**Issue by joe0BAB** [docker/desktop-action#2]
Thanks for this awesome github action! It makes setting up UI e2e ci tests for docker desktop extensions much easier. 

If possible, it would be great if it could also support linux runners so I could use it eg on Ubuntu machines.

**Comment by benja-M-1** [comment]
This is done in v0.2.0 https://github.com/docker/desktop-action/releases/tag/v0.2.0 but with large Linux runners only.
See https://github.blog/changelog/2023-02-23-hardware-accelerated-android-virtualization-on-actions-windows-and-linux-larger-hosted-runners/
