### ISSUE TITLE
feature request: pin versions

### ISSUE THREAD

**Issue by nicks** [docker/desktop-action#4]
Currently, desktop-action always downloads the most recent stable version of docker desktop. It'd be great if:

1) I could pin to an old version, to ensure that new versions don't accidentally break my CI
2) I could deliberately pin to a Release Candidate, so I can easily test my code against new docker desktop versions before they're released.

:pray: :pray: :pray:

**Comment by benja-M-1** [comment]
This is available from https://github.com/docker/desktop-action/releases/tag/v0.3.0
